// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/gitpushy/pave/cmd/pave/templates/pkg/internal/databases/maindb/ent/runtime.go

const (
	Version = "v0.12.2"                                         // Version of ent codegen.
	Sum     = "h1:Ndl/JvCX76xCtUDlrUfMnOKBRodAtxE5yfGYxjbOxmM=" // Sum of ent codegen.
)
